import os
import sys
import pandas as pd

# Setup path to import your core config tools
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from config import call_llm

print("--- Step 1: Reading Final Hybrid ML Scores ---")
data_path = "data/ml_final_scored_transactions.csv"

if not os.path.exists(data_path):
    print(f"❌ Error: {data_path} not found. Run core/model.py first!")
    sys.exit()

df = pd.read_csv(data_path)

# Extract operational pipeline metrics
total_records = len(df)
total_flags = int(df['ml_flag'].sum())
true_positives = int(((df['ml_flag'] == 1) & (df['is_suspicious'] == 1)).sum())
false_positives = int(((df['ml_flag'] == 1) & (df['is_suspicious'] == 0)).sum())
false_negatives = int(((df['ml_flag'] == 0) & (df['is_suspicious'] == 1)).sum())

# Isolate the highest-risk alerts generated by the machine learning algorithm
top_alerts = df[df['ml_flag'] == 1].nlargest(3, 'anomaly_score')
alert_summary = top_alerts[['txn_id', 'amount', 'txn_type', 'anomaly_score']].to_string()

print("--- Step 2: Requesting Compliance Summary from NVIDIA NIM ---")
prompt = f"""
Our Hybrid XGBoost-Isolation Forest AML production model has finished processing. 
Here are the performance audit metrics:
- Total Scored Logs: {total_records}
- Total Alerts Flagged: {total_flags}
- True Positives Caught: {true_positives}
- False Positives (Clean logs flagged): {false_positives}
- Missed Violations (False Negatives): {false_negatives}

Top 3 Highest-Risk Anomaly Profiles:
{alert_summary}

Please generate an official, structured Compliance Audit Summary Report. 
Include:
1. An executive summary evaluation of the model's deployment readiness.
2. A technical assessment explaining why a hybrid approach (supervised + unsupervised) successfully mitigated false alarms.
3. Next-step recommendations for an investigator handling the top 3 high-score alerts.
"""

# Call the API using your specialized Compliance Manager persona
report_content = call_llm(prompt=prompt, system_prompt="You are an expert Chief Anti-Money Laundering Compliance Officer and Model Risk Auditor.")

print("\n=== AML Compliance Audit Report ===")
print(report_content)

# Save the final text record out to your project folder
report_path = "artifacts/aml_compliance_report.txt"
with open(report_path, "w", encoding="utf-8") as f:
    f.write(report_content)
print(f"\n💾 Document successfully saved to disc at: {report_path}")
